# Generated by Django 3.1.4 on 2020-12-26 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
